version: 0.0
os: linux
files:
  - source: /src/
    destination: /var/www/html/
permissions:
  - object: /var/www
    owner: "apache"
    group: "root"
hooks:
  BeforeInstall:
    - location: scripts/check-dependencies.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/configure.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 120
      runas: root